version: "3.8"
services:
  nginx-php:
    build:
      context: ./docker
      dockerfile: alpine.armhf.Dockerfile
    image: dawsba/pi-alpine-nginx-php:1.0
    expose:
      - 80/tcp
      - 80/udp
    networks:
      - frontend
    depends_on:
      - mysql
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3