version: "2.4"
services:
  proxy:
    image: braingamer/nginx-proxy-arm
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - frontend
  mysql:
    image: hypriot/rpi-mysql
    expose:
      - 3306
    volumes:
      - ./DatabaseRepository:/var/lib/mysql
    networks:
      - frontend
    environment:
      - MYSQL_DATABASE=${PROJECT_MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${PROJECT_MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${PROJECT_MYSQL_USER}
      - MYSQL_PASSWORD=${PROJECT_MYSQL_PASSWORD}
  nginx-php:
    extends:
      file: common-services.yml
      service: nginx-php
    volumes:
      - ./${PROJECT_PROJECT1_FOLDER}:/var/www/html
    environment:
      - VIRTUAL_HOST=${PROJECT_PROJECT1_VHOST}
  creativeneon_nginx:
    extends:
      file: common-services.yml
      service: nginx-php
    environment:
      - VIRTUAL_HOST=${PROJECT_CREATIVENEON_VHOST}
    volumes:
      - ./creativeneon/creativeneon_old/public_html:/var/www/html
  php-my-admin:
    image: jackgruber/phpmyadmin
    expose:
      - 80
    depends_on:
      - mysql
    networks:
      - frontend
    environment:
      - PMA_HOST=mysql
      - VIRTUAL_HOST=${PROJECT_PROJECT1_PMA}
  symfony_php:
    build: ./php-fpm
    expose:
      - 9000
      - 9001
    volumes:
      - ./symfony:/var/www/symfony:cached
      - ./logs/symfony:/var/www/symfony/var/log:cached
    depends_on:
      - mysql
    networks:
      - frontend
  symfony_nginx:
    extends:
      file: common-services.yml
      service: nginx-php
    depends_on:
      - symfony_php
    environment:
      - VIRTUAL_HOST=${PROJECT_SYMFONY_VHOST}
    volumes:
      - ./logs/nginx:/var/log/nginx:cached
      - ./symfony:/var/www/html:cached
  elasticsearch:
    image: armhfbuild/elasticsearch
    environment:
      discovery.type: "single-node"
    expose:
      - 9200
    networks:
      frontend:
        aliases:
          - "elasticsearch"
  logstash:
    image: armhfbuild/logstash
    depends_on:
      - elasticsearch
    volumes:
      - ./elk/logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml:cached
      - ./elk/logstash/conf.d:/etc/logstash/conf.d:cached
      - ./logs/symfony:/var/www/symfony/var/log:cached
      - ./logs/nginx:/var/log/nginx:cached
    networks:
      - frontend
  kibana:
    depends_on:
      - elasticsearch
    image: armhfbuild/kibana
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - frontend
    expose:
      - 81
      - 5601

networks:
  frontend: